#!/bin/bash

sai_chroot() {
	chroot $DESTDIR "$@"
}

rc_conf() {
	sed -i -e "s|^$1=.*|$1=$2|" $DESTDIR/etc/rc.conf
}

inform() {
	tput setaf 4
	echo ":: $1"
	tput sgr0
	sleep 1
}

# chroot_mount()
# prepares target system as a chroot
#
chroot_mount() {
    [ -e "$DESTDIR/sys" ] || mkdir "$DESTDIR/sys"
    [ -e "$DESTDIR/proc" ] || mkdir "$DESTDIR/proc"
    [ -e "$DESTDIR/dev" ] || mkdir "$DESTDIR/dev"
    mount -t sysfs sysfs "$DESTDIR/sys"
    mount -t proc proc "$DESTDIR/proc"
    mount -o bind /dev "$DESTDIR/dev"
}

# chroot_umount()
# tears down chroot in target system
#
chroot_umount() {
    umount $DESTDIR/proc $DESTDIR/sys $DESTDIR/dev
}

sai_report() {
	is_ok "sai_partition" $sai_partition_ret
	is_ok "sai_installpkgs" $sai_installpkgs_ret
	is_ok "sai_config" $sai_config_ret
	is_ok "sai_initcpio" $sai_initcpio_ret
	is_ok "sai_bootloader" $sai_bootloader_ret
}

# $1 var
is_ok() {
	echo -n "$1: "
	if [ "$2" == "0" ]; then
		echo "success"
	else
		echo "failed"
	fi
}
